# Generated by cucumber-sinatra. (2013-12-14 12:45:11 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/generic_heroku.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

require 'coveralls'
Coveralls.wear!

Capybara.app = GenericHeroku

class GenericHerokuWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  GenericHerokuWorld.new
end
